{{- if .Values.kafka.enabled }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: combined
  namespace: {{ include "meridian.namespace" . }}
  labels:
    strimzi.io/cluster: meridian
    {{- include "meridian.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: persistent-claim
    size: {{ .Values.kafka.storage.size }}
    deleteClaim: false
  resources:
    {{- toYaml .Values.kafka.resources | nindent 4 }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: meridian
  namespace: {{ include "meridian.namespace" . }}
  labels:
    {{- include "meridian.labels" . | nindent 4 }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
{{- end }}
