apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "meridian.namespace" . }}
  labels:
    {{- include "meridian.labels" . | nindent 4 }}
    # Label required for Dynatrace OneAgent injection
    dynatrace.com/inject: "true"
